server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level.com.netflix.eureka: OFF
  level.com.netflix.discovery: OFF
---
spring:
  profiles: openshift
server:
  port: 8080