server:
  port: 8181
spring:
  application:
    name: movie-registry
my:
  var: Hello World
---
spring:
  profiles: openshift
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8080/eureka
  instance:
    hostname: movie-repository-spring-cloud.apps.10.2.2.2.xip.io
    nonSecurePort: 80