server:
  port: 8080
spring:
  application:
    name: movie-client
---
spring:
  profiles: openshift
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8080/eureka
  instance:
    nonSecurePort: 8080