server:
  port: 8181
spring:
  application:
    name: movie-registry
my:
  var: Hello World
---
spring:
  profiles: openshift
server:
  port: 8080
eureka:
  client:
    service-url: http://eureka-server:8080/eureka