server:
  port: 8484
spring:
  application:
    name: turbine
turbine:
  appConfig: movie-client,actor-client
  clusterNameExpression: new String("default")

---
spring:
  profiles: openshift
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8080/eureka
  instance:
    nonSecurePort: 8080